# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart Formatter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Format
        run: dart format .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: Dart Formatter[bot]
          committer_email: actions@github.com
          message: "Format .dart files"
          add: "*.dart"
